#ifndef RING_BUFFER_RETURN_CODES_H
#define RING_BUFFER_RETURN_CODES_H

enum RingBufferReturnCode {
    RBUFFER_OK = 0,
    RBUFFER_ERROR_MEM_ALLOC,
    RBUFFER_ERROR_INVALID_PARAM,
    RBUFFER_ERROR_IS_EMPTY,
    RBUFFER_ERROR_RESIZE_FAIL,
};

#endif